logging:
  level:
    com.bupt.buptcar.dao: debug # 输出mybatis执行的sql
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/buptcar?serverTimezone=UTC&rewriteBatchedStatements=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 0
  mvc:
    hiddenmethod.filter.enabled: true
# 配置mybatis规则
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: false